export const FAKE_POPULARS = [
  {
    backdrop_path: "/218ZehBKlH8efPRRccmB7bu0oLQ.jpg",
    first_air_date: "2023-09-25",
    genre_ids: [35, 9648, 10766, 18],
    id: 219109,
    name: "Elas por Elas",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Elas por Elas",
    overview: "",
    popularity: 1868.924,
    poster_path: "/hCSH5KvSqShWXhFiXr88wtJXwlO.jpg",
    vote_average: 9.5,
    vote_count: 4,
  },
  {
    backdrop_path: "/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg",
    first_air_date: "1952-12-26",
    genre_ids: [10763],
    id: 94722,
    name: "Tagesschau",
    origin_country: ["DE"],
    original_language: "de",
    original_name: "Tagesschau",
    overview: "German daily news program, the oldest still existing program on German television.",
    popularity: 2487.148,
    poster_path: "/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg",
    vote_average: 7.4,
    vote_count: 153,
  },
];
