export const FAKE_POPULARS = [
  {
    backdrop_path: "/218ZehBKlH8efPRRccmB7bu0oLQ.jpg",
    first_air_date: "2023-09-25",
    genre_ids: [35, 9648, 10766, 18],
    id: 219109,
    name: "Elas por Elas",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Elas por Elas",
    overview:
      "Some overview, some overview, some overview, some overview, some overview, some overview",
    popularity: 1868.924,
    poster_path: "/hCSH5KvSqShWXhFiXr88wtJXwlO.jpg",
    vote_average: 9.5,
    vote_count: 4,
  },
  {
    backdrop_path: "/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg",
    first_air_date: "1952-12-26",
    genre_ids: [10763],
    id: 94722,
    name: "Tagesschau",
    origin_country: ["DE"],
    original_language: "de",
    original_name: "Tagesschau",
    overview: "German daily news program, the oldest still existing program on German television.",
    popularity: 2487.148,
    poster_path: "/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg",
    vote_average: 7.4,
    vote_count: 153,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    id: 119051,
    name: "Wednesday",
    original_language: "en",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 35],
    popularity: 271.066,
    first_air_date: "2022-11-23",
    vote_average: 8.542,
    vote_count: 7568,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/Aa9TLpNpBMyRkD8sPJ7ACKLjt0l.jpg",
    id: 94997,
    name: "House of the Dragon",
    original_language: "en",
    original_name: "House of the Dragon",
    overview:
      "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
    poster_path: "/1X4h40fcB4WWUmIBK0auT4zRBAV.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 371.266,
    first_air_date: "2022-08-21",
    vote_average: 8.442,
    vote_count: 3459,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/1rO4xoCo4Z5WubK0OwdVll3DPYo.jpg",
    id: 84773,
    name: "The Lord of the Rings: The Rings of Power",
    original_language: "en",
    original_name: "The Lord of the Rings: The Rings of Power",
    overview:
      "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
    poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
    media_type: "tv",
    genre_ids: [10759, 10765, 18],
    popularity: 283.992,
    first_air_date: "2022-09-01",
    vote_average: 7.4,
    vote_count: 2233,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/bebZzFw1mBzF9UwCO3ocW0PIIby.jpg",
    id: 210232,
    name: "The Watcher",
    original_language: "en",
    original_name: "The Watcher",
    overview:
      "A family moves into their suburban dream home, only to discover they've inherited a nightmare.",
    poster_path: "/6RrseODZo2e66XOzC1XMzMuecnf.jpg",
    media_type: "tv",
    genre_ids: [18, 9648],
    popularity: 115.654,
    first_air_date: "2022-10-13",
    vote_average: 7.322,
    vote_count: 477,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    id: 100088,
    name: "The Last of Us",
    original_language: "en",
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 431.687,
    first_air_date: "2023-01-15",
    vote_average: 8.657,
    vote_count: 4127,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rpTpgiwj63N2f6HnB5SKhei5N80.jpg",
    id: 83659,
    name: "Guillermo del Toro's Cabinet of Curiosities",
    original_language: "en",
    original_name: "Guillermo del Toro's Cabinet of Curiosities",
    overview:
      "Bizarre nightmares unfold in eight tales of terror in this visually stunning, spine-tingling horror collection curated by Guillermo del Toro.",
    poster_path: "/a91e9hpWwfCqxJI4xM9Q2RhuxgI.jpg",
    media_type: "tv",
    genre_ids: [18, 9648],
    popularity: 180.247,
    first_air_date: "2022-10-25",
    vote_average: 7.653,
    vote_count: 634,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/42iDbOtqWqPvI3FnP3KafLFrQq.jpg",
    id: 209167,
    name: "Conversations with a Killer: The Jeffrey Dahmer Tapes",
    original_language: "en",
    original_name: "Conversations with a Killer: The Jeffrey Dahmer Tapes",
    overview:
      "Serial killer Jeffrey Dahmer confesses to his gruesome crimes in unguarded interviews, offering an unsettling view into a disturbed mind.",
    poster_path: "/5BTn4GxWL48BP8OkfiatxZ6qpuE.jpg",
    media_type: "tv",
    genre_ids: [99, 80],
    popularity: 43.086,
    first_air_date: "2022-10-07",
    vote_average: 7.964,
    vote_count: 194,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 804.503,
    first_air_date: "2011-04-17",
    vote_average: 8.442,
    vote_count: 21986,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg",
    id: 1396,
    name: "Breaking Bad",
    original_language: "en",
    original_name: "Breaking Bad",
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 529.434,
    first_air_date: "2008-01-20",
    vote_average: 8.891,
    vote_count: 12504,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 471.925,
    first_air_date: "2016-07-15",
    vote_average: 8.624,
    vote_count: 16238,
    origin_country: ["US"],
  },
];
